#!/bin/bash

#Set default shell
export SHELL=/bin/zsh
# Set default editor
export EDITOR=nvim
# Set default browser
export BROWSER=firefox
# Set cache to RAM disk
export XDG_CACHE_HOME=/dev/shm
# Set config directory
export XDG_CONFIG_HOME=$HOME/.config
# Set data directory
export XDG_DATA_HOME=$HOME/.local/share/

# Set theme
export THEME=DARK

xrdb -load ~/.Xresources &

xset -dpms 	#Turn off DPMS
# set mouse speed
setxkbmap us

start-pulseaudio-x11 &
dunst &


exec bspwm

